[2025-03-14 15:11:54,812: INFO: stage_03_data_validation: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:11:54,813: ERROR: stage_03_data_validation: [Errno 2] No such file or directory: 'config/config.yaml']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 39, in <module>
    obj.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 15, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/config/configuration.py", line 16, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(mlProject.utils.common.read_yaml) at 0x104413f60>", line 33, in read_yaml
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/utils/common.py", line 35, in read_yaml
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/utils/common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2025-03-14 15:24:46,069: INFO: stage_03_data_validation: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:24:46,069: INFO: stage_03_data_validation: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:24:46,069: ERROR: stage_03_data_validation: [Errno 2] No such file or directory: 'config/config.yaml']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 39, in <module>
    obj.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 15, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/config/configuration.py", line 16, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(mlProject.utils.common.read_yaml) at 0x106c2bf60>", line 33, in read_yaml
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/utils/common.py", line 35, in read_yaml
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/utils/common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2025-03-14 15:24:46,069: ERROR: stage_03_data_validation: [Errno 2] No such file or directory: 'config/config.yaml']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 39, in <module>
    obj.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 15, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/config/configuration.py", line 16, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(mlProject.utils.common.read_yaml) at 0x106677f60>", line 33, in read_yaml
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/utils/common.py", line 35, in read_yaml
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/utils/common.py", line 28, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
