[2025-03-14 05:34:54,497: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 05:34:54,499: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 05:34:54,499: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 05:34:54,500: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 05:34:54,500: INFO: common: created directory at: artifacts]
[2025-03-14 05:34:54,500: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 05:34:54,621: ERROR: main: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1319, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1365, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1314, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1074, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1018, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1460, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1046, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1317, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
[2025-03-14 05:37:27,544: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 05:37:27,546: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 05:37:27,547: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 05:37:27,547: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 05:37:27,547: INFO: common: created directory at: artifacts]
[2025-03-14 05:37:27,547: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 05:37:28,015: ERROR: main: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1319, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1365, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1314, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1074, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1018, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1460, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1046, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1317, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
[2025-03-14 05:38:20,347: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 05:38:20,349: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 05:38:20,350: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 05:38:20,350: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 05:38:20,350: INFO: common: created directory at: artifacts]
[2025-03-14 05:38:20,351: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 05:38:20,645: ERROR: main: HTTP Error 401: Unauthorized]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 16, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
[2025-03-14 05:43:26,116: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 05:43:26,118: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 05:43:26,119: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 05:43:26,119: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 05:43:26,120: INFO: common: created directory at: artifacts]
[2025-03-14 05:43:26,120: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 05:43:26,710: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Fri, 14 Mar 2025 09:43:26 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=522=pMpwuoXbu0YMCKgY4hcY6UZeXlgHr1_GtiM9XJrZaF-86bPscNVaekr8ZNGAVTnA1wyv11ZQbzNLkeTxw2r9ufTcUsLfKqCBzLFUfjRtnhV406j-2GirkWlXxdAx0Dqkwtj_UFgSaU61PeI-lVATJXSxaofiFwXslwHiug6_hmmIFwn3tIEA8ONCGdIMYfsCBA; expires=Sat, 13-Sep-2025 09:43:26 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2025-03-14 05:43:26,711: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-03-14 05:48:54,276: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 05:48:54,277: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 05:48:54,278: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 05:48:54,279: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 05:48:54,279: INFO: common: created directory at: artifacts]
[2025-03-14 05:48:54,279: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 05:48:54,651: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Fri, 14 Mar 2025 09:48:54 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=522=VuZ2i9LriSHy6qN_Blhc0pthAfeOWzBdC_sw5gxledurDlgdkXfHEsrseIw_x0TV9WNQl3crViT6O1uZd7EscBrExrNUhdzJTwPnS7wfQWhUKDkTmxy5kFM2dIrFhiRn8_Ukud4feXxRto0JTOTQOIIZkfRbfOrwoM7lQdg4Ak4snfiClrhN3tiGMC_NLVeu; expires=Sat, 13-Sep-2025 09:48:54 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2025-03-14 05:48:54,651: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-03-14 05:50:38,111: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 05:50:38,112: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 05:50:38,112: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 05:50:38,113: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 05:50:38,113: INFO: common: created directory at: artifacts]
[2025-03-14 05:50:38,113: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 05:50:38,488: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Fri, 14 Mar 2025 09:50:38 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=522=2fQBBhEdyOIOGc05iU6-6M6wSyz3DEzBibMc8n0ikysX4HqmlMgcG3sWvnVYZX2SttjoQ8vqeL2-biPbAsRPfHUjcYrgqdryxiwmE85HpcnguqvN8ZU8TkZ2KKn_kLc_aSZ0wB2fyuXqlFG0s2fL83zpChQENlxccvH5iB7jHkXr4XPQFS4sk78JZOBS3ojRKA; expires=Sat, 13-Sep-2025 09:50:38 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2025-03-14 05:50:38,489: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-03-14 06:02:14,375: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 06:02:14,376: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 06:02:14,377: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 06:02:14,378: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 06:02:14,378: INFO: common: created directory at: artifacts]
[2025-03-14 06:02:14,378: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 06:02:14,555: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
X-GUploader-UploadID: AKDAyIs6AIm9suW4nEDf5V0gtolHWnyTIZCRtiAjTYo0fczQNa-9QqdNypAsJyLRpM7E9cq_l0gvrA0
Content-Type: text/html; charset=utf-8
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site
Content-Security-Policy: sandbox allow-scripts allow-forms allow-downloads
Content-Security-Policy: require-trusted-types-for 'script';report-uri /_/DriveUntrustedContentHttp/cspreport
Content-Security-Policy: script-src 'report-sample' 'nonce-ZslWiSCDXXo0lKEkmvsyIA' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/DriveUntrustedContentHttp/cspreport;worker-src 'self'
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Fri, 14 Mar 2025 10:02:14 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Cross-Origin-Opener-Policy: same-origin
Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-wow64=*, ch-ua-form-factors=*, ch-ua-platform=*, ch-ua-platform-version=*
Accept-CH: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-WoW64, Sec-CH-UA-Form-Factors, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
Cross-Origin-Resource-Policy: same-site
reporting-endpoints: default="/_/DriveUntrustedContentHttp/web-reports?context=eJzj0tDikmLw15Bi6PHYxTQBiFf_PMe6Hoj3bDrPegCIFeWvsaoBsRAPx7K_5_exCWy4t2sSk5JqUn5hfEpRZllqRklJQWJBZnFqUVlqUbyRgZGpgbGBmZ6BUXyBIQC1oiNH"
Content-Length: 2467
Server: UploadServer
Set-Cookie: NID=522=oeOk_5gOKVtdq67Xsmj-P5bRibTYLaocosrggvwi1k9HWDrJ2-4QbO5rY3YfwFclZC9PxGXKYlQvVZRdjkGOvCbKstdQmbAsuvvziSm0ZKjqoRNPO98oDyFuP3uKF1bexlntkzUQWxHZfcbgz8j___BuS-dbVGXgQcU14gl_8ll1bta6r__ovLUVccIzgkgCXg; expires=Sat, 13-Sep-2025 10:02:14 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Connection: close

]
[2025-03-14 06:02:14,555: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 43, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2025-03-14 10:31:59,541: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 10:31:59,541: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 10:31:59,543: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 10:31:59,544: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 10:31:59,544: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 10:31:59,544: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 10:31:59,545: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 10:31:59,545: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 10:31:59,545: INFO: common: created directory at: artifacts]
[2025-03-14 10:31:59,545: INFO: common: created directory at: artifacts]
[2025-03-14 10:31:59,545: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 10:31:59,545: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 10:31:59,954: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 42, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1320, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2025-03-14 10:32:00,177: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 42, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1320, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2025-03-14 10:40:47,388: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 10:40:47,389: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 10:40:47,390: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 10:40:47,390: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 10:40:47,391: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 10:40:47,391: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 10:40:47,392: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 10:40:47,392: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 10:40:47,392: INFO: common: created directory at: artifacts]
[2025-03-14 10:40:47,392: INFO: common: created directory at: artifacts]
[2025-03-14 10:40:47,392: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 10:40:47,392: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 10:40:47,392: ERROR: main: name 'URL' is not defined]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 18, in download_file
    response = session.get(URL, params={"id": "1NNqlat1GdreoGhMTC5G8l5Q7XV-qtfVp"}, stream=True)
                           ^^^
NameError: name 'URL' is not defined
[2025-03-14 10:40:47,392: ERROR: main: name 'URL' is not defined]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 18, in download_file
    response = session.get(URL, params={"id": "1NNqlat1GdreoGhMTC5G8l5Q7XV-qtfVp"}, stream=True)
                           ^^^
NameError: name 'URL' is not defined
[2025-03-14 10:41:08,609: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 10:41:08,610: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 10:41:08,611: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 10:41:08,611: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 10:41:08,611: INFO: common: created directory at: artifacts]
[2025-03-14 10:41:08,611: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 10:41:08,960: INFO: data_ingestion: Downloaded from drive successfully!]
[2025-03-14 10:41:08,961: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 50, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1320, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2025-03-14 10:42:37,146: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 10:42:37,148: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 10:42:37,148: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 10:42:37,149: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 10:42:37,149: INFO: common: created directory at: artifacts]
[2025-03-14 10:42:37,149: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 10:42:37,449: INFO: data_ingestion: Downloaded from drive successfully!]
[2025-03-14 10:42:37,450: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 52, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1320, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2025-03-14 10:43:46,600: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 10:43:46,610: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 10:43:46,612: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 10:43:46,617: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 10:43:46,617: INFO: common: created directory at: artifacts]
[2025-03-14 10:43:46,617: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 10:51:06,491: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 10:51:06,493: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 10:51:06,494: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 10:51:06,494: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 10:51:06,494: INFO: common: created directory at: artifacts]
[2025-03-14 10:51:06,494: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 10:58:08,347: INFO: data_ingestion: Downloaded from drive successfully!]
[2025-03-14 10:58:08,349: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 12, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_ingestion.py", line 33, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1320, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2025-03-14 11:03:36,510: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 11:03:36,512: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 11:03:36,512: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 11:03:36,513: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 11:03:36,513: INFO: common: created directory at: artifacts]
[2025-03-14 11:03:36,513: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 11:12:01,846: INFO: data_ingestion: Downloaded from drive successfully!]
[2025-03-14 11:13:29,076: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 11:17:14,983: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 11:17:14,985: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 11:17:14,985: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 11:17:14,986: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 11:17:14,986: INFO: common: created directory at: artifacts]
[2025-03-14 11:17:14,986: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 11:17:14,987: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 11:17:14,987: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 11:17:14,988: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 11:17:14,988: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 11:17:14,989: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 11:17:14,989: INFO: common: created directory at: artifacts]
[2025-03-14 11:17:14,989: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 11:17:14,989: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/listings_*.json']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 22, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_02_data_validation.py", line 16, in main
    data_validation.validate_all_columns()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_validation.py", line 32, in validate_all_columns
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_validation.py", line 14, in validate_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/listings_*.json'
[2025-03-14 13:19:08,864: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 13:19:08,866: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:19:08,867: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:19:08,868: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:19:08,868: INFO: common: created directory at: artifacts]
[2025-03-14 13:19:08,868: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 13:19:08,868: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 13:19:08,868: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 13:19:08,869: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:19:08,870: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:19:08,870: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:19:08,870: INFO: common: created directory at: artifacts]
[2025-03-14 13:19:08,870: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 13:19:08,870: ERROR: main: DataTransformationConfig.__init__() missing 1 required positional argument: 'data_csv_path']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 22, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_02_data_transformation.py", line 14, in main
    data_transformation_config = config.get_data_validation_config()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/config/configuration.py", line 42, in get_data_validation_config
    data_validation_config = DataTransformationConfig(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataTransformationConfig.__init__() missing 1 required positional argument: 'data_csv_path'
[2025-03-14 13:22:35,786: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 13:22:35,787: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:22:35,788: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:22:35,789: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:22:35,789: INFO: common: created directory at: artifacts]
[2025-03-14 13:22:35,789: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 13:22:35,789: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 13:22:35,789: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 13:22:35,790: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:22:35,791: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:22:35,791: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:22:35,791: INFO: common: created directory at: artifacts]
[2025-03-14 13:22:35,791: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 13:22:35,791: ERROR: main: DataTransformationConfig.__init__() missing 1 required positional argument: 'data_csv_path']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 22, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_02_data_transformation.py", line 14, in main
    data_transformation_config = config.get_data_transformation_config()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/config/configuration.py", line 42, in get_data_transformation_config
    data_transformation_config = DataTransformationConfig(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataTransformationConfig.__init__() missing 1 required positional argument: 'data_csv_path'
[2025-03-14 13:23:29,314: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 13:23:29,316: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:23:29,316: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:23:29,317: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:23:29,317: INFO: common: created directory at: artifacts]
[2025-03-14 13:23:29,317: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 13:23:29,317: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 13:23:29,317: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 13:23:29,318: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:23:29,318: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:23:29,319: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:23:29,319: INFO: common: created directory at: artifacts]
[2025-03-14 13:23:29,319: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 13:23:29,320: ERROR: main: No objects to concatenate]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 22, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_02_data_transformation.py", line 16, in main
    data_transformation.load_and_save()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_transformation.py", line 59, in load_and_save
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_transformation.py", line 42, in load_and_save
    df_products = pd.concat(dfs, ignore_index=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 507, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2025-03-14 13:24:55,387: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 13:24:55,389: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:24:55,389: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:24:55,390: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:24:55,390: INFO: common: created directory at: artifacts]
[2025-03-14 13:24:55,390: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 13:24:55,390: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 13:24:55,390: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 13:24:55,391: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:24:55,391: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:24:55,392: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:24:55,392: INFO: common: created directory at: artifacts]
[2025-03-14 13:24:55,392: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 13:26:42,927: INFO: data_transformation: Saving data as csv under artifacts/data_validation/df_data.csv!]
[2025-03-14 13:26:44,753: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 13:27:05,427: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 13:27:05,428: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:27:05,429: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:27:05,430: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:27:05,430: INFO: common: created directory at: artifacts]
[2025-03-14 13:27:05,430: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 13:27:05,430: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 13:27:05,430: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 13:27:05,431: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:27:05,431: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:27:05,432: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:27:05,432: INFO: common: created directory at: artifacts]
[2025-03-14 13:27:05,432: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 13:27:20,173: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 13:27:20,174: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:27:20,175: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:27:20,175: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:27:20,175: INFO: common: created directory at: artifacts]
[2025-03-14 13:27:20,175: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 13:27:20,175: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 13:27:20,175: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 13:27:20,176: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:27:20,177: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:27:20,177: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:27:20,177: INFO: common: created directory at: artifacts]
[2025-03-14 13:27:20,177: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 13:30:01,678: INFO: data_transformation: Saving data as csv under artifacts/data_validation/df_data.csv!]
[2025-03-14 13:30:01,728: ERROR: main: Cannot save file into a non-existent directory: 'artifacts/data_validation']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 22, in <module>
    data_transformation.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_02_data_transformation.py", line 16, in main
    data_transformation.load_and_save()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_transformation.py", line 59, in load_and_save
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_transformation.py", line 55, in load_and_save
    df_products.to_csv(self.config.data_csv_path, index=False)
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'artifacts/data_validation'
[2025-03-14 13:31:21,375: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 13:31:21,377: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:31:21,377: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:31:21,378: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:31:21,378: INFO: common: created directory at: artifacts]
[2025-03-14 13:31:21,378: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 13:31:21,378: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 13:31:21,378: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 13:31:21,379: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 13:31:21,380: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:31:21,380: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:31:21,380: INFO: common: created directory at: artifacts]
[2025-03-14 13:31:21,380: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 13:32:53,543: INFO: data_transformation: Saving data as csv under artifacts/data_validation/df_data.csv!]
[2025-03-14 13:32:55,208: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 14:40:10,346: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 14:40:10,348: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 14:40:10,349: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:40:10,350: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:40:10,350: INFO: common: created directory at: artifacts]
[2025-03-14 14:40:10,350: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 14:40:10,350: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 14:40:10,350: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 14:40:10,351: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 14:40:10,351: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:40:10,352: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:40:10,352: INFO: common: created directory at: artifacts]
[2025-03-14 14:40:10,352: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 14:41:46,813: INFO: data_transformation: Saving data as csv under artifacts/data_validation/df_data.csv!]
[2025-03-14 14:41:48,373: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 14:41:48,373: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 14:41:48,375: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 14:41:48,376: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:41:48,377: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:41:48,377: INFO: common: created directory at: artifacts]
[2025-03-14 14:41:48,377: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 14:43:16,457: INFO: data_transformation: Saving data as csv under artifacts/data_validation/df_data.csv!]
[2025-03-14 14:43:18,799: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 15:06:35,788: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:06:35,790: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:06:35,790: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:06:35,791: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:06:35,791: INFO: common: created directory at: artifacts]
[2025-03-14 15:06:35,791: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:06:35,792: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:06:35,792: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:06:35,793: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:06:35,793: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:06:35,794: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:06:35,794: INFO: common: created directory at: artifacts]
[2025-03-14 15:06:35,794: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:06:35,794: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:06:35,794: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:06:35,795: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:06:35,796: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:06:35,796: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:06:35,796: INFO: common: created directory at: artifacts]
[2025-03-14 15:06:35,796: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:06:35,796: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 15:12:55,383: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:12:55,391: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:12:55,393: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:12:55,397: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:12:55,398: INFO: common: created directory at: artifacts]
[2025-03-14 15:12:55,398: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:12:55,398: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:12:55,398: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:12:55,406: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:12:55,407: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:12:55,411: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:12:55,412: INFO: common: created directory at: artifacts]
[2025-03-14 15:12:55,412: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:12:55,412: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:12:55,412: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:12:55,419: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:12:55,421: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:12:55,425: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:12:55,425: INFO: common: created directory at: artifacts]
[2025-03-14 15:12:55,425: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:12:55,426: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 15:13:55,349: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:13:55,349: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:13:55,358: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:13:55,358: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:13:55,360: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:13:55,360: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:13:55,365: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:13:55,365: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:13:55,365: INFO: common: created directory at: artifacts]
[2025-03-14 15:13:55,365: INFO: common: created directory at: artifacts]
[2025-03-14 15:13:55,365: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:13:55,365: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:13:55,365: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:13:55,365: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:13:55,365: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:13:55,365: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:13:55,373: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:13:55,373: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:13:55,375: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:13:55,375: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:13:55,379: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:13:55,379: INFO: common: created directory at: artifacts]
[2025-03-14 15:13:55,379: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:13:55,379: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:13:55,380: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:13:55,380: INFO: common: created directory at: artifacts]
[2025-03-14 15:13:55,380: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:13:55,380: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:13:55,380: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:13:55,380: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:13:55,387: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:13:55,388: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:13:55,389: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:13:55,389: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:13:55,393: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:13:55,393: INFO: common: created directory at: artifacts]
[2025-03-14 15:13:55,394: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:13:55,394: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 15:13:55,394: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:13:55,394: INFO: common: created directory at: artifacts]
[2025-03-14 15:13:55,394: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:13:55,394: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 15:14:16,486: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:14:16,494: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:14:16,496: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:14:16,500: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:14:16,501: INFO: common: created directory at: artifacts]
[2025-03-14 15:14:16,501: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:14:16,501: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:14:16,501: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:14:16,509: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:14:16,510: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:14:16,515: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:14:16,515: INFO: common: created directory at: artifacts]
[2025-03-14 15:14:16,515: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:14:16,515: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:14:16,515: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:14:16,523: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:14:16,524: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:14:16,529: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:14:16,529: INFO: common: created directory at: artifacts]
[2025-03-14 15:14:16,529: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 15:14:27,411: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 15:24:54,429: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:24:54,438: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:24:54,440: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:24:54,444: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:24:54,445: INFO: common: created directory at: artifacts]
[2025-03-14 15:24:54,445: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:24:54,446: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:24:54,446: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:24:54,454: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:24:54,455: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:24:54,459: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:24:54,460: INFO: common: created directory at: artifacts]
[2025-03-14 15:24:54,460: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:24:54,461: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:24:54,461: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:24:54,469: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:24:54,470: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:24:54,474: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:24:54,475: INFO: common: created directory at: artifacts]
[2025-03-14 15:24:54,475: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 15:25:15,888: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 15:26:43,364: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:26:43,373: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:26:43,374: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:26:43,379: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:26:43,383: INFO: common: created directory at: artifacts]
[2025-03-14 15:26:43,383: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:26:43,383: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:26:43,383: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:26:43,392: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:26:43,393: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:26:43,398: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:26:43,399: INFO: common: created directory at: artifacts]
[2025-03-14 15:26:43,399: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:26:43,399: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:26:43,399: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:26:43,408: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:26:43,410: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:26:43,415: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:26:43,415: INFO: common: created directory at: artifacts]
[2025-03-14 15:26:43,415: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 15:26:51,930: ERROR: stage_03_data_validation: [Errno 2] No such file or directory: 'artifacts/data_ingestion/images.csv']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 20, in main
    data_validation.merge_dataframes()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_validation.py", line 17, in merge_dataframes
    df_images = pd.read_csv(self.config.images_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/images.csv'
[2025-03-14 15:26:51,939: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/images.csv']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 32, in <module>
    data_validation.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 25, in main
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_03_data_validation.py", line 20, in main
    data_validation.merge_dataframes()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_validation.py", line 17, in merge_dataframes
    df_images = pd.read_csv(self.config.images_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/images.csv'
[2025-03-14 15:27:36,989: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:27:36,998: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:27:36,999: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:27:37,004: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:27:37,005: INFO: common: created directory at: artifacts]
[2025-03-14 15:27:37,005: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:27:37,005: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:27:37,005: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:27:37,013: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:27:37,014: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:27:37,019: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:27:37,019: INFO: common: created directory at: artifacts]
[2025-03-14 15:27:37,019: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:27:37,019: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:27:37,019: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:27:37,027: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:27:37,029: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:27:37,033: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:27:37,033: INFO: common: created directory at: artifacts]
[2025-03-14 15:27:37,033: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 15:27:45,859: INFO: data_validation: Shape of merged products: (422403, 28)]
[2025-03-14 15:27:46,108: INFO: data_validation: Null values count by columns: brand                  303815
bullet_point           323103
color                  323900
item_id                274701
item_name              299669
item_weight            316209
model_name             347732
model_number           298347
product_type           274701
image_id                  575
item_keywords          314838
country                274701
marketplace            274701
domain_name            274701
material               375464
style                  391998
item_dimensions        379065
fabric_type            416851
product_description    420447
item_shape             418464
pattern                418928
finish_type            421048
spin_id                414181
model_year             414638
3dmodel_id             414443
height                    575
width                     575
image_path                575
dtype: int64]
[2025-03-14 15:27:46,183: INFO: data_validation: Shape of merged products: (147702, 28)]
[2025-03-14 15:27:46,598: INFO: data_validation: Shape of merged products after dropping null values in item_name: (122734, 29)]
[2025-03-14 15:27:48,503: INFO: data_validation: Shape of sample dataset: (20000, 6)]
[2025-03-14 15:27:48,520: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 15:29:58,126: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 15:29:58,128: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:29:58,129: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:29:58,129: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:29:58,129: INFO: common: created directory at: artifacts]
[2025-03-14 15:29:58,130: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 15:29:58,130: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 15:29:58,130: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 15:29:58,131: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:29:58,131: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:29:58,132: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:29:58,132: INFO: common: created directory at: artifacts]
[2025-03-14 15:29:58,132: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:29:58,132: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 15:29:58,132: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 15:29:58,133: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 15:29:58,133: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:29:58,134: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:29:58,134: INFO: common: created directory at: artifacts]
[2025-03-14 15:29:58,134: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 15:30:02,145: INFO: data_validation: Shape of merged products: (422403, 28)]
[2025-03-14 15:30:02,295: INFO: data_validation: Null values count by columns: brand                  303815
bullet_point           323103
color                  323900
item_id                274701
item_name              299669
item_weight            316209
model_name             347732
model_number           298347
product_type           274701
image_id                  575
item_keywords          314838
country                274701
marketplace            274701
domain_name            274701
material               375464
style                  391998
item_dimensions        379065
fabric_type            416851
product_description    420447
item_shape             418464
pattern                418928
finish_type            421048
spin_id                414181
model_year             414638
3dmodel_id             414443
height                    575
width                     575
image_path                575
dtype: int64]
[2025-03-14 15:30:02,355: INFO: data_validation: Shape of merged products: (147702, 28)]
[2025-03-14 15:30:02,755: INFO: data_validation: Shape of merged products after dropping null values in item_name: (122734, 29)]
[2025-03-14 15:30:04,562: INFO: data_validation: Shape of sample dataset: (20000, 6)]
[2025-03-14 15:30:04,658: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 16:24:52,210: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 16:24:52,212: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:24:52,213: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:24:52,214: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:24:52,214: INFO: common: created directory at: artifacts]
[2025-03-14 16:24:52,214: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 16:24:52,214: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 16:24:52,214: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 16:24:52,216: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:24:52,216: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:24:52,217: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:24:52,217: INFO: common: created directory at: artifacts]
[2025-03-14 16:24:52,217: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 16:24:52,217: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 16:24:52,217: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 16:24:52,219: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:24:52,219: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:24:52,220: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:24:52,220: INFO: common: created directory at: artifacts]
[2025-03-14 16:24:52,220: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 16:24:52,220: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 16:24:52,220: INFO: main: >>>>>> stage Data Visualization stage started <<<<<<]
[2025-03-14 16:24:52,222: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:24:52,222: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:24:52,223: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:24:52,223: INFO: common: created directory at: artifacts]
[2025-03-14 16:24:52,223: INFO: common: created directory at: artifacts/data_visualization]
[2025-03-14 16:24:52,986: ERROR: stage_04_data_visualization: DataVisualization.__init__() got an unexpected keyword argument 'master_data']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 18, in main
    data_visualization = DataVisualization(config=data_visualization_config, master_data=df_merged_master)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataVisualization.__init__() got an unexpected keyword argument 'master_data'
[2025-03-14 16:24:52,986: ERROR: main: DataVisualization.__init__() got an unexpected keyword argument 'master_data']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 43, in <module>
    data_visualization.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 27, in main
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 18, in main
    data_visualization = DataVisualization(config=data_visualization_config, master_data=df_merged_master)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataVisualization.__init__() got an unexpected keyword argument 'master_data'
[2025-03-14 16:25:09,073: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 16:25:09,075: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:25:09,075: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:25:09,076: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:25:09,076: INFO: common: created directory at: artifacts]
[2025-03-14 16:25:09,076: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 16:25:09,076: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 16:25:09,076: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 16:25:09,077: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:25:09,078: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:25:09,078: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:25:09,078: INFO: common: created directory at: artifacts]
[2025-03-14 16:25:09,078: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 16:25:09,078: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 16:25:09,078: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 16:25:09,080: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:25:09,080: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:25:09,080: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:25:09,081: INFO: common: created directory at: artifacts]
[2025-03-14 16:25:09,081: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 16:25:09,081: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 16:25:09,081: INFO: main: >>>>>> stage Data Visualization stage started <<<<<<]
[2025-03-14 16:25:09,082: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:25:09,082: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:25:09,083: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:25:09,083: INFO: common: created directory at: artifacts]
[2025-03-14 16:25:09,083: INFO: common: created directory at: artifacts/data_visualization]
[2025-03-14 16:25:09,893: ERROR: stage_04_data_visualization: DataVisualization.__init__() got an unexpected keyword argument 'master_data']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 18, in main
    data_visualization = DataVisualization(config=data_visualization_config, master_data=df_merged_master)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataVisualization.__init__() got an unexpected keyword argument 'master_data'
[2025-03-14 16:25:09,894: ERROR: main: DataVisualization.__init__() got an unexpected keyword argument 'master_data']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 43, in <module>
    data_visualization.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 27, in main
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 18, in main
    data_visualization = DataVisualization(config=data_visualization_config, master_data=df_merged_master)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataVisualization.__init__() got an unexpected keyword argument 'master_data'
[2025-03-14 16:25:39,902: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 16:25:39,904: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:25:39,904: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:25:39,905: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:25:39,905: INFO: common: created directory at: artifacts]
[2025-03-14 16:25:39,905: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 16:25:39,905: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 16:25:39,905: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 16:25:39,907: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:25:39,907: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:25:39,907: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:25:39,908: INFO: common: created directory at: artifacts]
[2025-03-14 16:25:39,908: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 16:25:39,908: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 16:25:39,908: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 16:25:39,909: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:25:39,909: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:25:39,910: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:25:39,910: INFO: common: created directory at: artifacts]
[2025-03-14 16:25:39,910: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 16:25:39,910: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 16:25:39,910: INFO: main: >>>>>> stage Data Visualization stage started <<<<<<]
[2025-03-14 16:25:39,911: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:25:39,911: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:25:39,912: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:25:39,912: INFO: common: created directory at: artifacts]
[2025-03-14 16:25:39,912: INFO: common: created directory at: artifacts/data_visualization]
[2025-03-14 16:25:44,053: ERROR: stage_04_data_visualization: Cannot take a larger sample than population when 'replace=False']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 23, in main
    data_visualization.generate_word_cloud_prod_description()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_visualization.py", line 92, in generate_word_cloud_prod_description
    text = " ".join(self.df_merged_master["product_description"].dropna().astype(str).sample(2000))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6118, in sample
    sampled_indices = sample.sample(obj_len, size, replace, weights, rs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/core/sample.py", line 152, in sample
    return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 1020, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
[2025-03-14 16:25:44,056: ERROR: main: Cannot take a larger sample than population when 'replace=False']
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 43, in <module>
    data_visualization.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 27, in main
    raise e
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_04_data_visualization.py", line 23, in main
    data_visualization.generate_word_cloud_prod_description()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/data_visualization.py", line 92, in generate_word_cloud_prod_description
    text = " ".join(self.df_merged_master["product_description"].dropna().astype(str).sample(2000))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6118, in sample
    sampled_indices = sample.sample(obj_len, size, replace, weights, rs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/pandas/core/sample.py", line 152, in sample
    return random_state.choice(obj_len, size=size, replace=replace, p=weights).astype(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 1020, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
[2025-03-14 16:28:24,500: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 16:28:24,504: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:28:24,505: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:28:24,506: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:28:24,506: INFO: common: created directory at: artifacts]
[2025-03-14 16:28:24,506: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 16:28:24,506: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 16:28:24,506: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 16:28:24,508: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:28:24,508: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:28:24,509: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:28:24,509: INFO: common: created directory at: artifacts]
[2025-03-14 16:28:24,509: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 16:28:24,509: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 16:28:24,509: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 16:28:24,510: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:28:24,511: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:28:24,511: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:28:24,512: INFO: common: created directory at: artifacts]
[2025-03-14 16:28:24,512: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 16:28:24,512: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 16:28:24,512: INFO: main: >>>>>> stage Data Visualization stage started <<<<<<]
[2025-03-14 16:28:24,513: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:28:24,514: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:28:24,514: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:28:24,514: INFO: common: created directory at: artifacts]
[2025-03-14 16:28:24,514: INFO: common: created directory at: artifacts/data_visualization]
[2025-03-14 16:28:29,766: INFO: main: >>>>>> stage Data Visualization stage completed <<<<<<

x==========x]
[2025-03-14 16:37:26,643: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 16:37:26,646: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:37:26,646: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:37:26,647: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:37:26,647: INFO: common: created directory at: artifacts]
[2025-03-14 16:37:26,647: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 16:37:26,647: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 16:37:26,647: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 16:37:26,649: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:37:26,649: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:37:26,650: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:37:26,650: INFO: common: created directory at: artifacts]
[2025-03-14 16:37:26,650: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 16:37:26,650: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 16:37:26,650: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 16:37:26,651: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:37:26,652: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:37:26,652: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:37:26,652: INFO: common: created directory at: artifacts]
[2025-03-14 16:37:26,652: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 16:37:26,652: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 16:37:26,652: INFO: main: >>>>>> stage Data Visualization stage started <<<<<<]
[2025-03-14 16:37:26,654: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:37:26,654: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:37:26,655: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:37:26,655: INFO: common: created directory at: artifacts]
[2025-03-14 16:37:26,655: INFO: common: created directory at: artifacts/data_visualization]
[2025-03-14 16:37:30,790: INFO: main: >>>>>> stage Data Visualization stage completed <<<<<<

x==========x]
[2025-03-14 16:43:09,804: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 16:43:09,807: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:43:09,807: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:43:09,808: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:43:09,808: INFO: common: created directory at: artifacts]
[2025-03-14 16:43:09,808: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 16:43:09,808: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 16:43:09,808: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 16:43:09,809: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:43:09,810: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:43:09,810: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:43:09,810: INFO: common: created directory at: artifacts]
[2025-03-14 16:43:09,810: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 16:43:09,810: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 16:43:09,810: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 16:43:09,812: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:43:09,812: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:43:09,813: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:43:09,813: INFO: common: created directory at: artifacts]
[2025-03-14 16:43:09,813: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 16:43:09,813: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 16:43:09,813: INFO: main: >>>>>> stage Data Visualization stage started <<<<<<]
[2025-03-14 16:43:09,814: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:43:09,814: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:43:09,815: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:43:09,815: INFO: common: created directory at: artifacts]
[2025-03-14 16:43:09,815: INFO: common: created directory at: artifacts/data_visualization]
[2025-03-14 16:43:13,734: INFO: main: >>>>>> stage Data Visualization stage completed <<<<<<

x==========x]
[2025-03-14 16:43:46,105: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 16:43:46,107: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:43:46,108: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:43:46,109: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:43:46,109: INFO: common: created directory at: artifacts]
[2025-03-14 16:43:46,109: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 16:43:46,109: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 16:43:46,109: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 16:43:46,110: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:43:46,111: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:43:46,111: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:43:46,111: INFO: common: created directory at: artifacts]
[2025-03-14 16:43:46,111: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 16:43:46,111: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 16:43:46,111: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 16:43:46,113: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:43:46,113: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:43:46,114: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:43:46,114: INFO: common: created directory at: artifacts]
[2025-03-14 16:43:46,114: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 16:43:46,114: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 16:43:46,114: INFO: main: >>>>>> stage Data Visualization stage started <<<<<<]
[2025-03-14 16:43:46,115: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 16:43:46,115: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 16:43:46,116: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 16:43:46,116: INFO: common: created directory at: artifacts]
[2025-03-14 16:43:46,116: INFO: common: created directory at: artifacts/data_visualization]
[2025-03-14 16:43:49,650: INFO: main: >>>>>> stage Data Visualization stage completed <<<<<<

x==========x]
[2025-03-14 20:43:19,882: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 20:43:19,884: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 20:43:19,885: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 20:43:19,886: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 20:43:19,886: INFO: common: created directory at: artifacts]
[2025-03-14 20:43:19,886: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 20:43:19,886: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 20:43:19,886: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 20:43:19,889: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 20:43:19,889: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 20:43:19,890: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 20:43:19,890: INFO: common: created directory at: artifacts]
[2025-03-14 20:43:19,891: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 20:43:19,891: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 20:43:19,891: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 20:43:19,892: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 20:43:19,893: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 20:43:19,894: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 20:43:19,894: INFO: common: created directory at: artifacts]
[2025-03-14 20:43:19,894: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 20:43:19,895: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 20:43:19,895: INFO: main: >>>>>> stage Data Visualization stage started <<<<<<]
[2025-03-14 20:43:19,896: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-14 20:43:19,896: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 20:43:19,897: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 20:43:19,897: INFO: common: created directory at: artifacts]
[2025-03-14 20:43:19,897: INFO: common: created directory at: artifacts/data_visualization]
[2025-03-14 20:43:24,630: INFO: main: >>>>>> stage Data Visualization stage completed <<<<<<

x==========x]
[2025-03-16 14:27:30,867: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-16 14:27:30,869: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-16 14:27:30,869: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-16 14:27:30,870: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-16 14:27:30,870: INFO: common: created directory at: artifacts]
[2025-03-16 14:27:30,870: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-16 14:28:00,671: ERROR: main: to() received an invalid combination of arguments - got (function), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 53, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_05_model_trainer.py", line 16, in main
    model_trainer_config.train()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/model_trainer.py", line 92, in train
    anchor_inputs = {key: value.squeeze().to(device) for key, value in
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: to() received an invalid combination of arguments - got (function), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)

[2025-03-16 14:34:38,197: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-16 14:34:38,199: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-16 14:34:38,200: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-16 14:34:38,200: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-16 14:34:38,200: INFO: common: created directory at: artifacts]
[2025-03-16 14:34:38,200: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-16 14:34:38,759: INFO: model_trainer: Initializing data for training]
[2025-03-16 14:35:07,629: INFO: model_trainer: Created triplet data for training]
[2025-03-16 14:35:07,630: INFO: model_trainer: Created triplet data for training]
[2025-03-16 14:35:07,669: ERROR: main: to() received an invalid combination of arguments - got (function, dtype=torch.dtype), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 53, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_05_model_trainer.py", line 16, in main
    model_trainer_config.train()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/model_trainer.py", line 94, in train
    anchor_inputs = {key: value.squeeze().to(device, dtype=torch.long) for key, value in
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: to() received an invalid combination of arguments - got (function, dtype=torch.dtype), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)

[2025-03-16 14:42:39,799: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-16 14:42:39,799: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-16 14:42:39,801: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-16 14:42:39,801: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-16 14:42:39,801: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-16 14:42:39,801: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-16 14:42:39,802: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-16 14:42:39,802: INFO: common: created directory at: artifacts]
[2025-03-16 14:42:39,802: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-16 14:42:39,802: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-16 14:42:39,802: INFO: common: created directory at: artifacts]
[2025-03-16 14:42:39,802: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-16 14:42:40,308: INFO: model_trainer: Initializing data for training]
[2025-03-16 14:42:40,308: INFO: model_trainer: Initializing data for training]
[2025-03-16 14:43:10,233: INFO: model_trainer: Created triplet data for training]
[2025-03-16 14:43:10,234: INFO: model_trainer: Created LoRA config: LoraConfig(peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, task_type=<TaskType.FEATURE_EXTRACTION: 'FEATURE_EXTRACTION'>, inference_mode=False, r=8, target_modules=None, lora_alpha=32, lora_dropout=0.1, fan_in_fan_out=False, bias='none', modules_to_save=None, init_lora_weights=True, layers_to_transform=None, layers_pattern=None)]
[2025-03-16 14:43:10,255: ERROR: main: to() received an invalid combination of arguments - got (function), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 53, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_05_model_trainer.py", line 16, in main
    model_trainer_config.train()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/model_trainer.py", line 80, in train
    peft_model.to(device)
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1302, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: to() received an invalid combination of arguments - got (function), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)

[2025-03-16 14:43:10,519: INFO: model_trainer: Created triplet data for training]
[2025-03-16 14:43:10,520: INFO: model_trainer: Created LoRA config: LoraConfig(peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, task_type=<TaskType.FEATURE_EXTRACTION: 'FEATURE_EXTRACTION'>, inference_mode=False, r=8, target_modules=None, lora_alpha=32, lora_dropout=0.1, fan_in_fan_out=False, bias='none', modules_to_save=None, init_lora_weights=True, layers_to_transform=None, layers_pattern=None)]
[2025-03-16 14:43:10,538: ERROR: main: to() received an invalid combination of arguments - got (function), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
]
Traceback (most recent call last):
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/main.py", line 53, in <module>
    data_ingestion.main()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/pipeline/stage_05_model_trainer.py", line 16, in main
    model_trainer_config.train()
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/src/mlProject/components/model_trainer.py", line 80, in train
    peft_model.to(device)
  File "/Users/vivekprabu/PycharmProjects/ShopTalk/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1302, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: to() received an invalid combination of arguments - got (function), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)

[2025-03-16 14:45:48,620: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-16 14:45:48,622: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-03-16 14:45:48,622: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-16 14:45:48,623: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-16 14:45:48,623: INFO: common: created directory at: artifacts]
[2025-03-16 14:45:48,623: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-16 14:45:49,019: INFO: model_trainer: Initializing data for training]
[2025-03-16 14:46:17,383: INFO: model_trainer: Created triplet data for training]
[2025-03-16 14:46:17,385: INFO: model_trainer: Created LoRA config: LoraConfig(peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, task_type=<TaskType.FEATURE_EXTRACTION: 'FEATURE_EXTRACTION'>, inference_mode=False, r=8, target_modules=None, lora_alpha=32, lora_dropout=0.1, fan_in_fan_out=False, bias='none', modules_to_save=None, init_lora_weights=True, layers_to_transform=None, layers_pattern=None)]
[2025-03-16 14:58:24,637: INFO: model_trainer: Epoch 1, Loss: 0.043135502338409425]
[2025-03-16 15:10:30,509: INFO: model_trainer: Epoch 2, Loss: 0.020102133560180663]
[2025-03-16 15:22:42,267: INFO: model_trainer: Epoch 3, Loss: 0.017448138427734374]
[2025-03-16 15:34:42,961: INFO: model_trainer: Epoch 4, Loss: 0.014838677763938903]
[2025-03-16 15:46:58,431: INFO: model_trainer: Epoch 5, Loss: 0.01328669695854187]
[2025-03-16 15:46:58,808: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
